dictionary1 = {
  "a": "Fish",
  "b": "Donkey",
  "c": "Duck",
  "d": "Cat",
  "e": "Dog",
  "f": "Horse",
  "g": "Rabbit",
  "h": "Emu",
  "i": "Cow",
  "j": "Sparrow",
  "k": "Pigeon",
  "l": "Hamster",
  "m": "Penguin",
  "n": "Sheep",
  "o": "Goat",
  "p": "Pig",
  "q": "Parrot",
  "r": "Oyster",
  "s": "Crab",
  "t": "Octopus",
  "u": "Dolphin",
  "v": "Whale",
  "w": "Eagle",
  "x": "Owl",
  "y": "Blackbird",
  "z": "Zebra",
  " ": "Snake",
  ".": "Rat"
}

dictionary2 = {
  "a": "alfa",
  "b": "bravo",
  "c": "charlie",
  "d": "delta",
  "e": "echo",
  "f": "foxtrot",
  "g": "golf",
  "h": "hotel",
  "i": "india",
  "j": "juliett",
  "k": "kilo",
  "l": "lima",
  "m": "mike",
  "n": "november",
  "o": "oscar",
  "p": "papa",
  "q": "quebec",
  "r": "romeo",
  "s": "sierra",
  "t": "tango",
  "u": "uniform",
  "v": "victor",
  "w": "whiskey",
  "x": "xray",
  "y": "yankee",
  "z": "Zulu",
  " ": " ",
  ".": "."
}

dictionary3 = {
  "a": "",
  "b": "",
  "c": "",
  "d": "",
  "e": "",
  "f": "",
  "g": "",
  "h": "",
  "i": "",
  "j": "",
  "k": "",
  "l": "",
  "m": "",
  "n": "",
  "o": "",
  "p": "",
  "q": "",
  "r": "",
  "s": "",
  "t": "",
  "u": "",
  "v": "",
  "w": "",
  "x": "",
  "y": "",
  "z": "",
  " ": "",
  ".": ""
}